version: "3"
services:
  postgresdb:
    image: postgres:12.3
    container_name: postgres-database
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: haxul
      POSTGRES_PASSWORD: password
      POSTGRES_DB: estimation-db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  redis:
    image: redis:6.0
    command: ["sh", "-c", "exec redis-server --requirepass \"redis_password\""]
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379