headhunter:
  baseUrl: https://api.hh.ru/
  cities:
    samara: 78
  taxRatePercentage: 13

currency:
  api:
    url: https://api.exchangeratesapi.io/latest

spring:
  datasource:
    url: jdbc:postgresql://${CONTAINER_DB:localhost}:5432/estimation-db
    username: haxul
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/db.changelog-master.xml

redis:
  port: 6379
  host: ${REDIS_CONTAINER:localhost}